### ISSUE TITLE
WordPress Plugin

### ISSUE THREAD

**Issue by Hank-Voight** [proxycheck/proxycheck-php#1]
The time and date in the statistics is not correct. It would be nicer if the plugin got the date and time from the WordPress settings.

**Comment by proxycheck** [comment]
We do not make the WordPress plugin you're referring to, in-fact we don't make any plugins for our service currently. The plugin you're probably referring to is Proxy & VPN Blocker for WordPress which has its own website here: https://pvb.ricksterm.net/

Apologies for the late reply to this ticket. We appear to not be receiving notifications from GitHub for new tickets.
