### ISSUE TITLE
Invalid IP Data

### ISSUE THREAD

**Issue by Nekiplay** [proxycheck/proxycheck-php#2]
IP: 93.75.178.250 is this is proxy SOCKS5
proxy server 49.12.4.194:17256

And I do not use proxy :)
![image](https://user-images.githubusercontent.com/35975332/84582222-c8305600-ae02-11ea-9e26-d996bfc1b382.png)

**Comment by proxycheck** [comment]
Please do not submit data issues to this issue tracker as this is for PHP library issues only. All reports about data can be submitted via email directly to us at support@proxycheck.io thank you.
