### ISSUE TITLE
Main source code

### ISSUE THREAD

**Issue by Jobians** [proxycheck/proxycheck-php#5]
Please can you give me the source code without Composer

**Comment by proxycheck** [comment]
You can use this file directly: https://github.com/proxycheck/proxycheck-php/blob/master/src/proxycheck.php

Just download the file, put it in the same folder as your own php file and then include it at the top of your file like so:

`include_once 'proxycheck.php';`

**Comment by Jobians** [comment]
I'm getting error

**Comment by proxycheck** [comment]
You'll need to share the error to receive support for it.

**Comment by Jobians** [comment]
How can I add it to my website without Composer

**Comment by proxycheck** [comment]
Jobians, the code here is more meant for developers, you will need PHP experience to use the code even without Composer. We would recommend looking for a plugin that integrates our API for your website or hiring a small developer.

**Comment by Jobians** [comment]
Is their any other way to stop vpn in my website
