### ISSUE TITLE
Update required? Is this maintained?

### ISSUE THREAD

**Issue by Pushkraj19** [proxycheck/proxycheck-php#7]
Hello,

_Note: Just want to know if this is maintained and safe to use?_

I am using wordpress plugin of proxycheck and can see there are lots of updates every month. and I am wondering is this package updated on time?

Please someone check if there are any new improvement required that has not reflected here on this package from wordpress plugin code?

**Comment by proxycheck** [comment]
It's still maintained yes, there just hasn't been the need for any updates lately :)

Also the plugin you speak of is third-party software and may not even use this library, we do not make any WordPress plugins etc

**Comment by Pushkraj19** [comment]
Thank you very much for clarification.
